### ISSUE TITLE
Syning labels over all repos

### ISSUE THREAD

**Issue by hendrikebbers** [hiero-ledger/governance#27]
In the past I used [netlify/sync-labels-action@v1 ](https://github.com/netlify/sync-labels-action) to sync labels over all repos in an org. Is that something that CoWarden can do, or should we set up an action using the netifly code?

**Comment by ryjones** [comment]
I think netlify is your best bet. you could also use the settings app, but if you have an action that works, go for it

**Comment by ryjones** [comment]
take a look here: https://github.com/organizations/hiero-ledger/settings/repository-defaults

**Comment by hendrikebbers** [comment]
@ryjones I do not have access to that link

**Comment by ryjones** [comment]
@hendrikebbers look now
